# Required when running from Docker
host: 0.0.0.0
force_polling: true

# Speed it up a buit
incremental: true

# Fail if front matter misbehaves
strict_front_matter: true

# How much to render? These all default to false
show_drafts: false
future: false
unpublished: false

# Make the machine talk to you
verbose: false
profile: true
