name: Build and Transfer Jekyll Site

on:
  push:
    branches:
      - main
      - master
      
env:
  ORIGIN: origin
  GITHUB_TOKEN: ${{secrets.API_TOKEN_GITHUB}}

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tell git who we are
        run: |
          set -ex
          git config --global user.name "carolineolivia"
          git config --global user.email "carolineolivia@outlook.dk"
          git config --global advice.skippedCherryPicks false
          
      - name: Do the build
        uses: docker://lakruzz/jekyll-plus:latest
        with:
          entrypoint: jekyll
          args: build -s . -d _site
        
      - name: Push changes to default target branch
        run: |
          git clone https://carolineolivia:${{secrets.API_TOKEN_GITHUB}}@github.com/carolineolivia/www.carolineolivia.dk.git
          cd www.carolineolivia.dk
          rm -rf *
          cp -r ../_site/* .
          git add -A .
          git commit -m "Update _site"
          git push -f